services:
  # --- MySQL 数据库服务 ---
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=xitemtask  # 自动创建数据库
    volumes:
      # 初始化脚本：放入此目录下的 .sql 文件会在首次启动时自动执行（宿主的./mysql/data为空时才执行）
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - xitem-network
    # 【关键】添加健康检查，确保数据库不仅能连，而且能处理请求
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s # 给数据库 30 秒的启动缓冲期(启动后的前 30 秒内，不管健康检查是否失败,都不记入失败次数)
      
    # --- Spring Boot 应用服务 ---
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xitem-app
    restart: always
    ports:
      - "9095:9095"  # 映射端口：宿主机端口:容器端口
    environment:
      # 核心配置：使用服务名 'mysql' 作为主机名，Docker 会自动解析
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/xitemtask?serverTimezone=Asia/Shanghai&useUnicode=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      # 指定激活的配置环境
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy #当 mysql 服务的健康检查通过（healthy）后，才启动 app，防止初始化脚本执行时间过长导致检查异常
    networks:
      - xitem-network

# --- 网络配置 ---
networks:
  xitem-network:
    driver: bridge