server.port=9095
# logging file path
logging.file.name=./logs/run.log
logging.logback.rollingpolicy.max-history=90
# 1-default(localhost) 2-filepathset path
filepath.type=1
filepath.path=
# mysql
# Do not submit IP address!!!
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/xitemtask?serverTimezone=Asia/Shanghai&useUnicode=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
# Do not submit password!!!
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=20
#spring.datasource.hikari.minimum-idle=10
# actable
actable.table.auto=update
actable.model.pack=com.xxsword.xitem.admin.domain.*.entity
actable.database.type=mysql
mybatis-plus.mapper-locations=classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
# multipart
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=256MB
spring.servlet.multipart.max-request-size=1024MB
#freemarker
spring.freemarker.request-context-attribute:ctx
spring.freemarker.cache=false
spring.freemarker.check-template-location=true
spring.freemarker.charset=UTF-8
spring.freemarker.content-type=text/html
spring.freemarker.expose-request-attributes=false
spring.freemarker.expose-session-attributes=false
spring.freemarker.expose-spring-macro-helpers=false
spring.freemarker.suffix=.ftl
spring.freemarker.settings.number_format=0.###############
# scheduling
scheduling.enabled=false